# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: projects/optimalleads/analytics/presentation/grpc/analytics_internal_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'projects/optimalleads/analytics/presentation/grpc/analytics_internal_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nRprojects/optimalleads/analytics/presentation/grpc/analytics_internal_service.proto\x12(optimalleads.analytics.presentation.grpc\x1a\x1cgoogle/protobuf/struct.proto\"\xd1\x01\n\x12IngestEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61ggregate_id\x18\x02 \x01(\t\x12\x12\n\nevent_name\x18\x03 \x01(\t\x12\x12\n\nevent_kind\x18\x04 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x05 \x01(\t\x12\x14\n\x0c\x63\x61usation_id\x18\x06 \x01(\t\x12\x13\n\x0boccurred_at\x18\x07 \x01(\t\x12(\n\x07payload\x18\x08 \x01(\x0b\x32\x17.google.protobuf.Struct\"%\n\x13IngestEventResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa7\x01\n\x18\x41nalyticsInternalService\x12\x8a\x01\n\x0bIngestEvent\x12<.optimalleads.analytics.presentation.grpc.IngestEventRequest\x1a=.optimalleads.analytics.presentation.grpc.IngestEventResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'projects.optimalleads.analytics.presentation.grpc.analytics_internal_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGESTEVENTREQUEST']._serialized_start=159
  _globals['_INGESTEVENTREQUEST']._serialized_end=368
  _globals['_INGESTEVENTRESPONSE']._serialized_start=370
  _globals['_INGESTEVENTRESPONSE']._serialized_end=407
  _globals['_ANALYTICSINTERNALSERVICE']._serialized_start=410
  _globals['_ANALYTICSINTERNALSERVICE']._serialized_end=577
# @@protoc_insertion_point(module_scope)
