# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: projects/optimalleads/leads/presentation/grpc/lead_internal_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'projects/optimalleads/leads/presentation/grpc/lead_internal_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nIprojects/optimalleads/leads/presentation/grpc/lead_internal_service.proto\x12$optimalleads.leads.presentation.grpc\"c\n!CreateLeadFromConversationRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\t\"F\n\x0cLeadResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05stage\x18\x03 \x01(\t\x12\r\n\x05notes\x18\x04 \x03(\t2\xb2\x01\n\x14LeadsInternalService\x12\x99\x01\n\x1a\x43reateLeadFromConversation\x12G.optimalleads.leads.presentation.grpc.CreateLeadFromConversationRequest\x1a\x32.optimalleads.leads.presentation.grpc.LeadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'projects.optimalleads.leads.presentation.grpc.lead_internal_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATELEADFROMCONVERSATIONREQUEST']._serialized_start=115
  _globals['_CREATELEADFROMCONVERSATIONREQUEST']._serialized_end=214
  _globals['_LEADRESPONSE']._serialized_start=216
  _globals['_LEADRESPONSE']._serialized_end=286
  _globals['_LEADSINTERNALSERVICE']._serialized_start=289
  _globals['_LEADSINTERNALSERVICE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
