# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from projects.optimalleads.leads.presentation.grpc import lead_internal_service_pb2 as projects_dot_optimalleads_dot_leads_dot_presentation_dot_grpc_dot_lead__internal__service__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in projects/optimalleads/leads/presentation/grpc/lead_internal_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LeadsInternalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLeadFromConversation = channel.unary_unary(
                '/optimalleads.leads.presentation.grpc.LeadsInternalService/CreateLeadFromConversation',
                request_serializer=projects_dot_optimalleads_dot_leads_dot_presentation_dot_grpc_dot_lead__internal__service__pb2.CreateLeadFromConversationRequest.SerializeToString,
                response_deserializer=projects_dot_optimalleads_dot_leads_dot_presentation_dot_grpc_dot_lead__internal__service__pb2.LeadResponse.FromString,
                _registered_method=True)


class LeadsInternalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateLeadFromConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeadsInternalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLeadFromConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLeadFromConversation,
                    request_deserializer=projects_dot_optimalleads_dot_leads_dot_presentation_dot_grpc_dot_lead__internal__service__pb2.CreateLeadFromConversationRequest.FromString,
                    response_serializer=projects_dot_optimalleads_dot_leads_dot_presentation_dot_grpc_dot_lead__internal__service__pb2.LeadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'optimalleads.leads.presentation.grpc.LeadsInternalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('optimalleads.leads.presentation.grpc.LeadsInternalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LeadsInternalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateLeadFromConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/optimalleads.leads.presentation.grpc.LeadsInternalService/CreateLeadFromConversation',
            projects_dot_optimalleads_dot_leads_dot_presentation_dot_grpc_dot_lead__internal__service__pb2.CreateLeadFromConversationRequest.SerializeToString,
            projects_dot_optimalleads_dot_leads_dot_presentation_dot_grpc_dot_lead__internal__service__pb2.LeadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
