@host = http://127.0.0.1:8001
@json = application/json
@conversationId = 08f452de-c4a5-441e-bf85-27b7afcfdf5b

### Health
GET {{host}}/health

### Create conversation 1
POST {{host}}/conversations
Content-Type: {{json}}

{
  "title": "Chat CQRS 1",
  "correlation_id": "chat-001"
}

### Create conversation 2
POST {{host}}/conversations
Content-Type: {{json}}

{
  "title": "Chat CQRS 2",
  "correlation_id": "chat-002"
}

### Create conversation 3
POST {{host}}/conversations
Content-Type: {{json}}

{
  "title": "Chat CQRS 3",
  "correlation_id": "chat-003"
}

### Create conversation 4
POST {{host}}/conversations
Content-Type: {{json}}

{
  "title": "Chat CQRS 4",
  "correlation_id": "chat-004"
}

### Create conversation 5
POST {{host}}/conversations
Content-Type: {{json}}

{
  "title": "Chat CQRS 5",
  "correlation_id": "chat-005"
}

### Get all conversations
GET {{host}}/conversations

### Get conversation by id
GET {{host}}/conversations/{{conversationId}}

### Update conversation by conversation_id (conversation_id is the resource id)
PUT {{host}}/conversations/{{conversationId}}
Content-Type: {{json}}

{
  "title": "Chat CQRS 2 updated",
  "messages": [
    "Hello from CQRS 2",
    "Second message from PUT",
    "Third message from PUT"
  ],
  "summary": "Updated from PUT",
  "correlation_id": "chat-002-modificat"
}

### Append message
POST {{host}}/conversations/{{conversationId}}/messages
Content-Type: {{json}}

{
  "message": "Hello from CQRS",
  "correlation_id": "chat-001"
}

### Get outbox entries
GET {{host}}/outbox

### Flush outbox
POST {{host}}/outbox/flush

### Delete conversation by conversation_id (conversation_id is the resource id)
DELETE {{host}}/conversations/{{conversationId}}
